=== agoston/whoisserver-legacy/src/defs/attributes.dtd
<!--  _________oOo_________
      DTD for RIPE attributes
      ottrey@ripe.net
      Tue Oct 12 13:22:07 CEST 1999
      _________oOo_________
-->

<!ELEMENT ripe_attributes  (ripe_attribute+)>
<!ATTLIST ripe_attributes
            version   CDATA     #REQUIRED
            author    CDATA     #IMPLIED
>

<!ENTITY % Status_t '(deprecated | valid | proposed)'>

<!ELEMENT ripe_attribute   (description, syntax, representation?, keys?, foreignkey?, dummify?)>
<!ATTLIST ripe_attribute
            name      CDATA       #REQUIRED
            xmlname   CDATA       #IMPLIED
            altName   CDATA       #IMPLIED
            code      ID          #REQUIRED
            status    %Status_t;             "valid"
>

<!ELEMENT description   (#PCDATA)> 

<!ELEMENT syntax        ((list|ripe-list)?, CDATA)>

<!ELEMENT dummify (filter | placeholder)>

<!ELEMENT list  EMPTY>

<!ELEMENT ripe-list EMPTY>

<!ENTITY % SQL_Keytype_t '(
  wk_name      |
  wk_nic_hdl   |
  wk_email     |
  wk_mntner    |
  wk_key_cert  |
  wk_ipaddress |
  wk_autnum    |
  wk_netname   |
  wk_net6name  |
  wk_limerick  |
  wk_domain    |
  wk_routesetname |
  wk_assetname |
  wk_asrange    |
  wk_filterset  |
  wk_peeringset |
  wk_rtrset
)'>

<!ENTITY % Radix_Keytype_t '(
  wk_iprange   |
  wk_ipprefix  |
  wk_ip6prefix |
  wk_ipaddress 
)'>

<!ELEMENT keys          ((foreign? | primary)?, ( queries?))>
<!ATTLIST keys
            searchable  (lookup | inverse | not) #REQUIRED
>

<!ELEMENT foreign       EMPTY>
<!ATTLIST foreign
            value     NMTOKEN     #REQUIRED
>

<!ELEMENT primary       EMPTY>

<!ENTITY % UD_Qtype_t '(
  ud_aux__  |
  ud_ax_pr  |
  ud_ax_mt  |
  ud_ax_mo  |
  ud_ax_mr  |
  ud_ax_mu  |
  ud_leaf_  |
  ud_lf_if  |
  ud_lf_rf  |
  ud_lf_at  |
  ud_lf_ot  |
  ud_lf_ay  |
  ud_main_  |
  ud_ma_rt  |
  ud_ma_or  |
  ud_ma_pr  |
  ud_ma_u2  |
  ud_ma_in  |
  ud_ma_i6  |
  ud_ma_ak  |
  ud_null_
)'>



<!ELEMENT queries     (sqlquery*, radixquery*)>

<!ELEMENT sqlquery    (#PCDATA)>
<!ATTLIST sqlquery
            keytype   %SQL_Keytype_t;          #REQUIRED
            class     NMTOKEN                  #IMPLIED     
>

<!ELEMENT radixquery  EMPTY>
<!ATTLIST radixquery
            keytype   %Radix_Keytype_t;        #REQUIRED
            class     NMTOKEN                  #IMPLIED
            space     (IP_V4 | IP_V6)          #REQUIRED            
>

<!ELEMENT representation     (sqltable, radixtrees?)>


<!ELEMENT sqltable (insert?, update?, dummy?, select?)>
<!ATTLIST sqltable
            name    CDATA       #REQUIRED
>    

<!ELEMENT insert        (#PCDATA)> 
<!ATTLIST insert
            qtype     %UD_Qtype_t;             #REQUIRED
>

<!ELEMENT update        (#PCDATA)> 
<!ATTLIST update
            qtype     %UD_Qtype_t;             #REQUIRED
>

<!ELEMENT dummy         (#PCDATA)> 
<!ATTLIST dummy
            qtype     %UD_Qtype_t;             #REQUIRED
>

<!ELEMENT select        (#PCDATA)> 
<!ATTLIST select
            qtype     %UD_Qtype_t;             #REQUIRED
>

<!ELEMENT radixtrees   (IP_V4?, IP_V6?)>
<!ATTLIST radixtrees
             family    (RX_FAM_IN | RX_FAM_RT)  #REQUIRED
>

<!ELEMENT IP_V4        (#PCDATA)> 
<!ELEMENT IP_V6        (#PCDATA)>

=== agoston/whoisserver-legacy/src/defs/attributes.xml
<!DOCTYPE ripe_attributes SYSTEM "attributes.dtd">

<ripe_attributes version="$Revision: 1.10 $" author="$Author: katie $">

  <ripe_attribute name="abuse-mailbox" code="am">
    <description>
   Specifies the e-mail address to which abuse complaints should be sent.
    </description>
    <syntax>e-mail</syntax>

    <representation>
    <sqltable name="abuse_mailbox">
      <insert qtype="ud_lf_ot">
        INSERT abuse_mailbox
        SET thread_id=%d, object_id=%ld, object_type=%d, abuse_mailbox='%s'
      </insert>
      <update qtype="ud_leaf_">
        UPDATE abuse_mailbox
        SET thread_id=%d
        WHERE object_id=%ld
        AND abuse_mailbox='%s'
      </update>
    </sqltable>
    </representation>

    <keys searchable="inverse">

      <queries>
        <sqlquery keytype="wk_email" class="ANY">
          SELECT object_id,0
          FROM   abuse_mailbox i
          WHERE  i.abuse_mailbox = '%s'
    AND  i.thread_id = 0
        </sqlquery>
      </queries>
    </keys>
  </ripe_attribute>

  <ripe_attribute name="address" code="ad">
    <description>
      Full postal address of a contact.
    </description>
    <syntax>free-form</syntax>
    <dummify>
        <filter>Dummy address for %s</filter>
    </dummify>
  </ripe_attribute>

  <ripe_attribute name="admin-c" code="ac">
    <description>
   References an on-site administrative contact.
    </description>
    <syntax>nic-handle</syntax>

    <representation> 
    <sqltable name="admin_c">
      <insert qtype="ud_aux__">
        INSERT admin_c 
        SELECT %d, %ld, person_role.object_id, %d 
        FROM person_role 
        WHERE person_role.nic_hdl='%s'
      </insert>
      <update qtype="ud_ax_pr">
        UPDATE admin_c
        SET thread_id=%d
        WHERE object_id=%ld
        AND pe_ro_id=%ld
      </update>
      <dummy qtype="ud_ax_pr">
        INSERT person_role 
        SET thread_id=%d, object_id=%ld, nic_hdl='%s', object_type=%d, dummy=1
      </dummy>
    </sqltable>
    </representation>
    <keys searchable="inverse">
      <foreign value="nh"/>
      
      <queries>
        <!-- Inverse name queries don't make sense, and are slow
        <sqlquery keytype="wk_name" class="ANY">
          SELECT i.object_id
          FROM   admin_c i, %s
          WHERE  %s
          AND    i.pe_ro_id = N00.object_id
	  AND	 i.thread_id = 0
        </sqlquery>
        -->
        <sqlquery keytype="wk_nic_hdl" class="ANY">
          SELECT i.object_id,0
          FROM   admin_c i, person_role
          WHERE  i.pe_ro_id = person_role.object_id
          AND    person_role.nic_hdl  = '%s'
	  AND	 i.thread_id = 0
        </sqlquery>
      </queries>
    </keys>
  </ripe_attribute>

  <ripe_attribute name="aggr-mtd" code="ag">
      <description>
   Specifies how the aggregate is generated.
      </description>
      <syntax>aggr-mtd</syntax>
  </ripe_attribute>

  <ripe_attribute name="aggr-bndry" code="ab">
      <description>
   Defines a set of ASes, which form the aggregation boundary.
      </description>
      <syntax>aggr-bndry</syntax>
  </ripe_attribute>

  <ripe_attribute name="alias" code="az">
     <description>
   The canonical DNS name for the router.
     </description>
     <syntax>domain-name</syntax>
  </ripe_attribute>

  <ripe_attribute name="as-name" code="aa">
      <description>
   A descriptive name associated with an AS.
      </description>
      <syntax>object-name</syntax>
   </ripe_attribute>


  <ripe_attribute name="as-set" code="as">
    <description>
   Defines the name of the set.
    </description>
    <syntax>as-set</syntax>

    <representation>
    <sqltable name="as_set">
      <insert qtype="ud_main_">
        INSERT as_set
        SET thread_id=%d, object_id=%ld, as_set='%s', dummy=0
      </insert>
      <update qtype="ud_main_">
        UPDATE as_set
        SET thread_id=%d
        WHERE object_id=%ld
      </update>
      <select qtype="ud_main_">
        as_set='%s' AND
      </select>
    </sqltable>
    </representation>

    <keys searchable="lookup">
      <primary/>

      <queries>
        <sqlquery keytype="wk_assetname">
          SELECT object_id,0
          FROM   as_set
          WHERE  as_set = '%s'
          AND    thread_id = 0
        </sqlquery>
      </queries>
    </keys>
  </ripe_attribute>

  <ripe_attribute name="auth" code="at">
    <description>
   Defines an authentication scheme to be used.
    </description>
    <syntax>auth-scheme</syntax>

    <representation>
    <sqltable name="auth">
      <insert qtype="ud_lf_at">
        INSERT auth
        SET thread_id=%d, object_id=%ld, object_type=%d, auth='%s'
      </insert>
      <update qtype="ud_leaf_">
        UPDATE auth
        SET thread_id=%d
        WHERE object_id=%ld
        AND auth='%s'
      </update>
    </sqltable>
    </representation>
    <keys searchable="inverse">
      <queries>
        <sqlquery keytype="wk_auth" class="mt">
          SELECT object_id,0
          FROM   auth
          WHERE  auth = '%s'
          AND    thread_id = 0
        </sqlquery>
      </queries>
    </keys>

  </ripe_attribute>

  <ripe_attribute name="author" code="ah">
    <description>
   References a limerick author.
    </description>
    <syntax>nic-handle</syntax>
    <representation>
      <sqltable name="author">
        <insert qtype="ud_aux__">
          INSERT author
          SELECT %d, %ld, person_role.object_id, %d
          FROM person_role
          WHERE person_role.nic_hdl='%s'
        </insert>
        <update qtype="ud_ax_pr">
          UPDATE author
          SET thread_id=%d
          WHERE object_id=%ld
          AND pe_ro_id=%ld
        </update>
        <dummy qtype="ud_ax_pr">
          INSERT person_role
          SET thread_id=%d, object_id=%ld, nic_hdl='%s', object_type=%d, dummy=1
        </dummy>
      </sqltable>
    </representation>
    <keys searchable="inverse">
      <foreign value="nh"/>
      <queries>
        <!-- Inverse name queries don't make sense, and are slow
        <sqlquery keytype="wk_name" class="ANY">
          SELECT i.object_id
          FROM   author i, %s
          WHERE  %s
          AND    i.pe_ro_id = N00.object_id
          AND    i.thread_id = 0
        </sqlquery>
        -->
        <sqlquery keytype="wk_nic_hdl" class="ANY">
          SELECT i.object_id,0
          FROM   person_role, author i
          WHERE  person_role.object_id = i.pe_ro_id
          AND    person_role.nic_hdl  = '%s'
          AND    i.thread_id = 0
        </sqlquery>
      </queries>
    </keys>
  </ripe_attribute>

  <ripe_attribute name="certif" code="ce">
     <description>
   Contains the public key.
     </description>
     <syntax>public-key</syntax>
  </ripe_attribute>

  <ripe_attribute name="changed" code="ch">
    <description>
   Specifies who submitted the update, and when the object was
   updated. 
   This attribute is filtered from the default whois output.
    </description>
    <syntax>changed</syntax>
  </ripe_attribute>

  <ripe_attribute xmlname="components-rt" name="components" code="co">
    <description>
   The "components:" attribute defines what component routes are
   used to form the aggregate.  
    </description>
    <syntax>components</syntax>
  </ripe_attribute>

  <ripe_attribute xmlname="components-r6" name="components" code="co">
    <description>
   The "components:" attribute defines what component routes are
   used to form the aggregate.
    </description>
    <syntax>components-r6</syntax>
  </ripe_attribute>

  <ripe_attribute name="country" code="cy">
    <description>
   Identifies the country.
    </description>
    <syntax>country-code</syntax>
  </ripe_attribute>

  <ripe_attribute name="default" code="df">
     <description>
   Specifies default routing policies.
     </description>
     <syntax>default</syntax>
  </ripe_attribute>
 
  <ripe_attribute name="mp-default" code="ma">
     <description>
   Specifies default multiprotocol routing policies.
     </description>
     <syntax>mp-default</syntax>
  </ripe_attribute>
 
  <ripe_attribute name="descr" code="de">
    <description>
   A short decription related to the object.
    </description>
    <syntax>free-form</syntax>
  </ripe_attribute>

  <ripe_attribute name="dom-net" code="di">
    <description>
   List of IP networks in a domain.
    </description>
    <syntax><ripe-list/>ipv4-address</syntax>
  </ripe_attribute>

  <ripe_attribute name="domain" code="dn">
    <description>
   Domain name.
    </description>
    <syntax>domain-name</syntax>

    <representation>
        <sqltable name="domain">
              <insert qtype="ud_main_">
                INSERT domain
                SET thread_id=%d, object_id=%ld, domain='%s'
              </insert>
              <update qtype="ud_main_"></update>
              <select qtype="ud_main_">
                domain='%s' AND
              </select>
        </sqltable>
        <radixtrees family="RX_FAM_RT">
             <IP_V4>
                SELECT domain.object_id,prefix,prefix_length,domain
                FROM inaddr_arpa,domain
                WHERE domain.object_id = inaddr_arpa.object_id
                AND   inaddr_arpa.thread_id = 0
             </IP_V4>
             <IP_V6>
                SELECT domain.object_id, msb, lsb, prefix_length, domain
                FROM ip6int,domain
                WHERE domain.object_id = ip6int.object_id
                AND ip6int.thread_id = 0
             </IP_V6>
        </radixtrees>
    </representation>

    <keys searchable="lookup">
      <primary/>

      <queries>
        <sqlquery keytype="wk_domain">
          SELECT object_id,0
          FROM   domain
          WHERE  domain = '%s'
          AND    thread_id = 0
        </sqlquery>
        <radixquery keytype="wk_iprange"   space="IP_V4" />
        <radixquery keytype="wk_ipprefix"  space="IP_V4" />
        <radixquery keytype="wk_ipaddress" space="IP_V4" />
        <radixquery keytype="wk_ip6prefix" space="IP_V6" />
